/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const AccountType = IDL.Variant({
  'loan' : IDL.Null,
  'investment' : IDL.Null,
  'credit_card' : IDL.Null,
  'bank_account' : IDL.Null,
});
export const CurrencyCode = IDL.Text;
export const Account = IDL.Record({
  'balance' : IDL.Int,
  'owner' : UserId,
  'name' : IDL.Text,
  'isShared' : IDL.Bool,
  'accountType' : AccountType,
  'currency' : CurrencyCode,
  'category' : IDL.Text,
});
export const Budget = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'month' : IDL.Nat,
  'actual' : IDL.Float64,
  'name' : IDL.Text,
  'plan' : IDL.Float64,
  'year' : IDL.Nat,
  'isActive' : IDL.Bool,
  'currency' : CurrencyCode,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const FinancialGoal = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'currency' : CurrencyCode,
  'targetDate' : Time,
  'current' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const RecurringTransactionFrequency = IDL.Variant({
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
  'biweekly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const StandingOrder = IDL.Record({
  'to' : Account,
  'internalId' : IDL.Text,
  'from' : Account,
  'test' : IDL.Bool,
  'currency' : CurrencyCode,
  'frequency' : RecurringTransactionFrequency,
  'amount' : IDL.Float64,
  'nextPaymentDate' : Time,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
  'transfer' : IDL.Null,
});
export const HouseholdId = IDL.Nat;
export const Transaction = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'transactionType' : TransactionType,
  'isRecurring' : IDL.Bool,
  'date' : Time,
  'note' : IDL.Text,
  'isShared' : IDL.Bool,
  'split' : IDL.Bool,
  'accountType' : AccountType,
  'currency' : CurrencyCode,
  'account' : IDL.Text,
  'category' : IDL.Text,
  'recurringFrequency' : IDL.Opt(RecurringTransactionFrequency),
  'budget' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Float64,
  'household' : IDL.Opt(HouseholdId),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func([Account], [], []),
  'addBudget' : IDL.Func([Budget], [], []),
  'addFinancialGoal' : IDL.Func([FinancialGoal], [], []),
  'addStandingOrder' : IDL.Func([StandingOrder], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAccountsByBalance' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllStandingOrders' : IDL.Func([], [IDL.Vec(StandingOrder)], ['query']),
  'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getBudgetsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Budget)], ['query']),
  'getBudgetsByPlan' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getBudgetsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Budget)], ['query']),
  'getBudgetsByYearMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Budget)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinancialGoals' : IDL.Func([], [IDL.Vec(FinancialGoal)], ['query']),
  'getFinancialGoalsByAmount' : IDL.Func(
      [],
      [IDL.Vec(FinancialGoal)],
      ['query'],
    ),
  'getFinancialGoalsByProgress' : IDL.Func(
      [],
      [IDL.Vec(FinancialGoal)],
      ['query'],
    ),
  'getStandingOrder' : IDL.Func([IDL.Text], [StandingOrder], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByAmount' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByBudget' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const AccountType = IDL.Variant({
    'loan' : IDL.Null,
    'investment' : IDL.Null,
    'credit_card' : IDL.Null,
    'bank_account' : IDL.Null,
  });
  const CurrencyCode = IDL.Text;
  const Account = IDL.Record({
    'balance' : IDL.Int,
    'owner' : UserId,
    'name' : IDL.Text,
    'isShared' : IDL.Bool,
    'accountType' : AccountType,
    'currency' : CurrencyCode,
    'category' : IDL.Text,
  });
  const Budget = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'month' : IDL.Nat,
    'actual' : IDL.Float64,
    'name' : IDL.Text,
    'plan' : IDL.Float64,
    'year' : IDL.Nat,
    'isActive' : IDL.Bool,
    'currency' : CurrencyCode,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const FinancialGoal = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'currency' : CurrencyCode,
    'targetDate' : Time,
    'current' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const RecurringTransactionFrequency = IDL.Variant({
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
    'biweekly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const StandingOrder = IDL.Record({
    'to' : Account,
    'internalId' : IDL.Text,
    'from' : Account,
    'test' : IDL.Bool,
    'currency' : CurrencyCode,
    'frequency' : RecurringTransactionFrequency,
    'amount' : IDL.Float64,
    'nextPaymentDate' : Time,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const HouseholdId = IDL.Nat;
  const Transaction = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'transactionType' : TransactionType,
    'isRecurring' : IDL.Bool,
    'date' : Time,
    'note' : IDL.Text,
    'isShared' : IDL.Bool,
    'split' : IDL.Bool,
    'accountType' : AccountType,
    'currency' : CurrencyCode,
    'account' : IDL.Text,
    'category' : IDL.Text,
    'recurringFrequency' : IDL.Opt(RecurringTransactionFrequency),
    'budget' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Float64,
    'household' : IDL.Opt(HouseholdId),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func([Account], [], []),
    'addBudget' : IDL.Func([Budget], [], []),
    'addFinancialGoal' : IDL.Func([FinancialGoal], [], []),
    'addStandingOrder' : IDL.Func([StandingOrder], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAccountsByBalance' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllStandingOrders' : IDL.Func([], [IDL.Vec(StandingOrder)], ['query']),
    'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getBudgetsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Budget)], ['query']),
    'getBudgetsByPlan' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getBudgetsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Budget)], ['query']),
    'getBudgetsByYearMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Budget)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinancialGoals' : IDL.Func([], [IDL.Vec(FinancialGoal)], ['query']),
    'getFinancialGoalsByAmount' : IDL.Func(
        [],
        [IDL.Vec(FinancialGoal)],
        ['query'],
      ),
    'getFinancialGoalsByProgress' : IDL.Func(
        [],
        [IDL.Vec(FinancialGoal)],
        ['query'],
      ),
    'getStandingOrder' : IDL.Func([IDL.Text], [StandingOrder], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByAmount' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByBudget' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };