/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'balance' : bigint,
  'owner' : UserId,
  'name' : string,
  'isShared' : boolean,
  'accountType' : AccountType,
  'currency' : CurrencyCode,
  'category' : string,
}
export type AccountType = { 'loan' : null } |
  { 'investment' : null } |
  { 'credit_card' : null } |
  { 'bank_account' : null };
export interface Budget {
  'id' : [] | [bigint],
  'month' : bigint,
  'actual' : number,
  'name' : string,
  'plan' : number,
  'year' : bigint,
  'isActive' : boolean,
  'currency' : CurrencyCode,
  'category' : string,
}
export type CurrencyCode = string;
export interface FinancialGoal {
  'name' : string,
  'isActive' : boolean,
  'currency' : CurrencyCode,
  'targetDate' : Time,
  'current' : number,
  'amount' : number,
}
export type HouseholdId = bigint;
export type RecurringTransactionFrequency = { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null } |
  { 'biweekly' : null } |
  { 'weekly' : null };
export interface StandingOrder {
  'to' : Account,
  'internalId' : string,
  'from' : Account,
  'test' : boolean,
  'currency' : CurrencyCode,
  'frequency' : RecurringTransactionFrequency,
  'amount' : number,
  'nextPaymentDate' : Time,
}
export type Time = bigint;
export interface Transaction {
  'id' : [] | [bigint],
  'transactionType' : TransactionType,
  'isRecurring' : boolean,
  'date' : Time,
  'note' : string,
  'isShared' : boolean,
  'split' : boolean,
  'accountType' : AccountType,
  'currency' : CurrencyCode,
  'account' : string,
  'category' : string,
  'recurringFrequency' : [] | [RecurringTransactionFrequency],
  'budget' : [] | [bigint],
  'amount' : number,
  'household' : [] | [HouseholdId],
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null } |
  { 'transfer' : null };
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<[Account], undefined>,
  'addBudget' : ActorMethod<[Budget], undefined>,
  'addFinancialGoal' : ActorMethod<[FinancialGoal], undefined>,
  'addStandingOrder' : ActorMethod<[StandingOrder], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAccounts' : ActorMethod<[], Array<Account>>,
  'getAccountsByBalance' : ActorMethod<[], Array<Account>>,
  'getAllStandingOrders' : ActorMethod<[], Array<StandingOrder>>,
  'getBudgets' : ActorMethod<[], Array<Budget>>,
  'getBudgetsByCategory' : ActorMethod<[string], Array<Budget>>,
  'getBudgetsByPlan' : ActorMethod<[], Array<Budget>>,
  'getBudgetsByYear' : ActorMethod<[bigint], Array<Budget>>,
  'getBudgetsByYearMonth' : ActorMethod<[bigint, bigint], Array<Budget>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinancialGoals' : ActorMethod<[], Array<FinancialGoal>>,
  'getFinancialGoalsByAmount' : ActorMethod<[], Array<FinancialGoal>>,
  'getFinancialGoalsByProgress' : ActorMethod<[], Array<FinancialGoal>>,
  'getStandingOrder' : ActorMethod<[string], StandingOrder>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactionsByAccount' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsByAmount' : ActorMethod<[], Array<Transaction>>,
  'getTransactionsByBudget' : ActorMethod<[bigint], Array<Transaction>>,
  'getTransactionsByCategory' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];