/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Account {
    balance: bigint;
    owner: UserId;
    name: string;
    isShared: boolean;
    accountType: AccountType;
    currency: CurrencyCode;
    category: string;
}
export interface StandingOrder {
    to: Account;
    internalId: string;
    from: Account;
    test: boolean;
    currency: CurrencyCode;
    frequency: RecurringTransactionFrequency;
    amount: number;
    nextPaymentDate: Time;
}
export type Time = bigint;
export type CurrencyCode = string;
export interface Transaction {
    id?: bigint;
    transactionType: TransactionType;
    isRecurring: boolean;
    date: Time;
    note: string;
    isShared: boolean;
    split: boolean;
    accountType: AccountType;
    currency: CurrencyCode;
    account: string;
    category: string;
    recurringFrequency?: RecurringTransactionFrequency;
    budget?: bigint;
    amount: number;
    household?: HouseholdId;
}
export type UserId = Principal;
export interface FinancialGoal {
    name: string;
    isActive: boolean;
    currency: CurrencyCode;
    targetDate: Time;
    current: number;
    amount: number;
}
export type HouseholdId = bigint;
export interface UserProfile {
    name: string;
}
export interface Budget {
    id?: bigint;
    month: bigint;
    actual: number;
    name: string;
    plan: number;
    year: bigint;
    isActive: boolean;
    currency: CurrencyCode;
    category: string;
}
export enum AccountType {
    loan = "loan",
    investment = "investment",
    credit_card = "credit_card",
    bank_account = "bank_account"
}
export enum RecurringTransactionFrequency {
    quarterly = "quarterly",
    monthly = "monthly",
    yearly = "yearly",
    daily = "daily",
    biweekly = "biweekly",
    weekly = "weekly"
}
export enum TransactionType {
    expense = "expense",
    income = "income",
    transfer = "transfer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAccount(account: Account): Promise<void>;
    addBudget(budget: Budget): Promise<void>;
    addFinancialGoal(goal: FinancialGoal): Promise<void>;
    addStandingOrder(standingOrder: StandingOrder): Promise<void>;
    addTransaction(transaction: Transaction): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAccounts(): Promise<Array<Account>>;
    getAccountsByBalance(): Promise<Array<Account>>;
    getAllStandingOrders(): Promise<Array<StandingOrder>>;
    getBudgets(): Promise<Array<Budget>>;
    getBudgetsByCategory(category: string): Promise<Array<Budget>>;
    getBudgetsByPlan(): Promise<Array<Budget>>;
    getBudgetsByYear(year: bigint): Promise<Array<Budget>>;
    getBudgetsByYearMonth(year: bigint, month: bigint): Promise<Array<Budget>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFinancialGoals(): Promise<Array<FinancialGoal>>;
    getFinancialGoalsByAmount(): Promise<Array<FinancialGoal>>;
    getFinancialGoalsByProgress(): Promise<Array<FinancialGoal>>;
    getStandingOrder(standingOrderId: string): Promise<StandingOrder>;
    getTransactions(): Promise<Array<Transaction>>;
    getTransactionsByAccount(account: string): Promise<Array<Transaction>>;
    getTransactionsByAmount(): Promise<Array<Transaction>>;
    getTransactionsByBudget(budget: bigint): Promise<Array<Transaction>>;
    getTransactionsByCategory(category: string): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Account as _Account, AccountType as _AccountType, Budget as _Budget, CurrencyCode as _CurrencyCode, HouseholdId as _HouseholdId, RecurringTransactionFrequency as _RecurringTransactionFrequency, StandingOrder as _StandingOrder, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAccount(arg0: Account): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(to_candid_Account_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(to_candid_Account_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBudget(arg0: Budget): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBudget(to_candid_Budget_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBudget(to_candid_Budget_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFinancialGoal(arg0: FinancialGoal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFinancialGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFinancialGoal(arg0);
            return result;
        }
    }
    async addStandingOrder(arg0: StandingOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStandingOrder(to_candid_StandingOrder_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStandingOrder(to_candid_StandingOrder_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_Transaction_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_Transaction_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccounts();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccounts();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccountsByBalance(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountsByBalance();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountsByBalance();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStandingOrders(): Promise<Array<StandingOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStandingOrders();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStandingOrders();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgets(): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgets();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgets();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetsByCategory(arg0: string): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetsByCategory(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetsByCategory(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetsByPlan(): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetsByPlan();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetsByPlan();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetsByYear(arg0: bigint): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetsByYear(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetsByYear(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetsByYearMonth(arg0: bigint, arg1: bigint): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetsByYearMonth(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetsByYearMonth(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialGoals(): Promise<Array<FinancialGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialGoals();
            return result;
        }
    }
    async getFinancialGoalsByAmount(): Promise<Array<FinancialGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialGoalsByAmount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialGoalsByAmount();
            return result;
        }
    }
    async getFinancialGoalsByProgress(): Promise<Array<FinancialGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialGoalsByProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialGoalsByProgress();
            return result;
        }
    }
    async getStandingOrder(arg0: string): Promise<StandingOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandingOrder(arg0);
                return from_candid_StandingOrder_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandingOrder(arg0);
            return from_candid_StandingOrder_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByAccount(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByAccount(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByAccount(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByAmount(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByAmount();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByAmount();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByBudget(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByBudget(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByBudget(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByCategory(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_AccountType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Account_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Budget_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Budget): Budget {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringTransactionFrequency_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringTransactionFrequency): RecurringTransactionFrequency {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StandingOrder_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StandingOrder): StandingOrder {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecurringTransactionFrequency]): RecurringTransactionFrequency | null {
    return value.length === 0 ? null : from_candid_RecurringTransactionFrequency_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HouseholdId]): HouseholdId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    owner: _UserId;
    name: string;
    isShared: boolean;
    accountType: _AccountType;
    currency: _CurrencyCode;
    category: string;
}): {
    balance: bigint;
    owner: UserId;
    name: string;
    isShared: boolean;
    accountType: AccountType;
    currency: CurrencyCode;
    category: string;
} {
    return {
        balance: value.balance,
        owner: value.owner,
        name: value.name,
        isShared: value.isShared,
        accountType: from_candid_AccountType_n20(_uploadFile, _downloadFile, value.accountType),
        currency: value.currency,
        category: value.category
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: _Account;
    internalId: string;
    from: _Account;
    test: boolean;
    currency: _CurrencyCode;
    frequency: _RecurringTransactionFrequency;
    amount: number;
    nextPaymentDate: _Time;
}): {
    to: Account;
    internalId: string;
    from: Account;
    test: boolean;
    currency: CurrencyCode;
    frequency: RecurringTransactionFrequency;
    amount: number;
    nextPaymentDate: Time;
} {
    return {
        to: from_candid_Account_n18(_uploadFile, _downloadFile, value.to),
        internalId: value.internalId,
        from: from_candid_Account_n18(_uploadFile, _downloadFile, value.from),
        test: value.test,
        currency: value.currency,
        frequency: from_candid_RecurringTransactionFrequency_n25(_uploadFile, _downloadFile, value.frequency),
        amount: value.amount,
        nextPaymentDate: value.nextPaymentDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: [] | [bigint];
    month: bigint;
    actual: number;
    name: string;
    plan: number;
    year: bigint;
    isActive: boolean;
    currency: _CurrencyCode;
    category: string;
}): {
    id?: bigint;
    month: bigint;
    actual: number;
    name: string;
    plan: number;
    year: bigint;
    isActive: boolean;
    currency: CurrencyCode;
    category: string;
} {
    return {
        id: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.id)),
        month: value.month,
        actual: value.actual,
        name: value.name,
        plan: value.plan,
        year: value.year,
        isActive: value.isActive,
        currency: value.currency,
        category: value.category
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: [] | [bigint];
    transactionType: _TransactionType;
    isRecurring: boolean;
    date: _Time;
    note: string;
    isShared: boolean;
    split: boolean;
    accountType: _AccountType;
    currency: _CurrencyCode;
    account: string;
    category: string;
    recurringFrequency: [] | [_RecurringTransactionFrequency];
    budget: [] | [bigint];
    amount: number;
    household: [] | [_HouseholdId];
}): {
    id?: bigint;
    transactionType: TransactionType;
    isRecurring: boolean;
    date: Time;
    note: string;
    isShared: boolean;
    split: boolean;
    accountType: AccountType;
    currency: CurrencyCode;
    account: string;
    category: string;
    recurringFrequency?: RecurringTransactionFrequency;
    budget?: bigint;
    amount: number;
    household?: HouseholdId;
} {
    return {
        id: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.id)),
        transactionType: from_candid_TransactionType_n37(_uploadFile, _downloadFile, value.transactionType),
        isRecurring: value.isRecurring,
        date: value.date,
        note: value.note,
        isShared: value.isShared,
        split: value.split,
        accountType: from_candid_AccountType_n20(_uploadFile, _downloadFile, value.accountType),
        currency: value.currency,
        account: value.account,
        category: value.category,
        recurringFrequency: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.recurringFrequency)),
        budget: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.budget)),
        amount: value.amount,
        household: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.household))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loan: null;
} | {
    investment: null;
} | {
    credit_card: null;
} | {
    bank_account: null;
}): AccountType {
    return "loan" in value ? AccountType.loan : "investment" in value ? AccountType.investment : "credit_card" in value ? AccountType.credit_card : "bank_account" in value ? AccountType.bank_account : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quarterly: null;
} | {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} | {
    biweekly: null;
} | {
    weekly: null;
}): RecurringTransactionFrequency {
    return "quarterly" in value ? RecurringTransactionFrequency.quarterly : "monthly" in value ? RecurringTransactionFrequency.monthly : "yearly" in value ? RecurringTransactionFrequency.yearly : "daily" in value ? RecurringTransactionFrequency.daily : "biweekly" in value ? RecurringTransactionFrequency.biweekly : "weekly" in value ? RecurringTransactionFrequency.weekly : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
} | {
    transfer: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : "transfer" in value ? TransactionType.transfer : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Account>): Array<Account> {
    return value.map((x)=>from_candid_Account_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StandingOrder>): Array<StandingOrder> {
    return value.map((x)=>from_candid_StandingOrder_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Budget>): Array<Budget> {
    return value.map((x)=>from_candid_Budget_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n35(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Account_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Budget_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Budget): _Budget {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringTransactionFrequency_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringTransactionFrequency): _RecurringTransactionFrequency {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_StandingOrder_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StandingOrder): _StandingOrder {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    transactionType: TransactionType;
    isRecurring: boolean;
    date: Time;
    note: string;
    isShared: boolean;
    split: boolean;
    accountType: AccountType;
    currency: CurrencyCode;
    account: string;
    category: string;
    recurringFrequency?: RecurringTransactionFrequency;
    budget?: bigint;
    amount: number;
    household?: HouseholdId;
}): {
    id: [] | [bigint];
    transactionType: _TransactionType;
    isRecurring: boolean;
    date: _Time;
    note: string;
    isShared: boolean;
    split: boolean;
    accountType: _AccountType;
    currency: _CurrencyCode;
    account: string;
    category: string;
    recurringFrequency: [] | [_RecurringTransactionFrequency];
    budget: [] | [bigint];
    amount: number;
    household: [] | [_HouseholdId];
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        transactionType: to_candid_TransactionType_n13(_uploadFile, _downloadFile, value.transactionType),
        isRecurring: value.isRecurring,
        date: value.date,
        note: value.note,
        isShared: value.isShared,
        split: value.split,
        accountType: to_candid_AccountType_n3(_uploadFile, _downloadFile, value.accountType),
        currency: value.currency,
        account: value.account,
        category: value.category,
        recurringFrequency: value.recurringFrequency ? candid_some(to_candid_RecurringTransactionFrequency_n9(_uploadFile, _downloadFile, value.recurringFrequency)) : candid_none(),
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        amount: value.amount,
        household: value.household ? candid_some(value.household) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    owner: UserId;
    name: string;
    isShared: boolean;
    accountType: AccountType;
    currency: CurrencyCode;
    category: string;
}): {
    balance: bigint;
    owner: _UserId;
    name: string;
    isShared: boolean;
    accountType: _AccountType;
    currency: _CurrencyCode;
    category: string;
} {
    return {
        balance: value.balance,
        owner: value.owner,
        name: value.name,
        isShared: value.isShared,
        accountType: to_candid_AccountType_n3(_uploadFile, _downloadFile, value.accountType),
        currency: value.currency,
        category: value.category
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    month: bigint;
    actual: number;
    name: string;
    plan: number;
    year: bigint;
    isActive: boolean;
    currency: CurrencyCode;
    category: string;
}): {
    id: [] | [bigint];
    month: bigint;
    actual: number;
    name: string;
    plan: number;
    year: bigint;
    isActive: boolean;
    currency: _CurrencyCode;
    category: string;
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        month: value.month,
        actual: value.actual,
        name: value.name,
        plan: value.plan,
        year: value.year,
        isActive: value.isActive,
        currency: value.currency,
        category: value.category
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Account;
    internalId: string;
    from: Account;
    test: boolean;
    currency: CurrencyCode;
    frequency: RecurringTransactionFrequency;
    amount: number;
    nextPaymentDate: Time;
}): {
    to: _Account;
    internalId: string;
    from: _Account;
    test: boolean;
    currency: _CurrencyCode;
    frequency: _RecurringTransactionFrequency;
    amount: number;
    nextPaymentDate: _Time;
} {
    return {
        to: to_candid_Account_n1(_uploadFile, _downloadFile, value.to),
        internalId: value.internalId,
        from: to_candid_Account_n1(_uploadFile, _downloadFile, value.from),
        test: value.test,
        currency: value.currency,
        frequency: to_candid_RecurringTransactionFrequency_n9(_uploadFile, _downloadFile, value.frequency),
        amount: value.amount,
        nextPaymentDate: value.nextPaymentDate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringTransactionFrequency): {
    quarterly: null;
} | {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} | {
    biweekly: null;
} | {
    weekly: null;
} {
    return value == RecurringTransactionFrequency.quarterly ? {
        quarterly: null
    } : value == RecurringTransactionFrequency.monthly ? {
        monthly: null
    } : value == RecurringTransactionFrequency.yearly ? {
        yearly: null
    } : value == RecurringTransactionFrequency.daily ? {
        daily: null
    } : value == RecurringTransactionFrequency.biweekly ? {
        biweekly: null
    } : value == RecurringTransactionFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} | {
    transfer: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value == TransactionType.transfer ? {
        transfer: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    loan: null;
} | {
    investment: null;
} | {
    credit_card: null;
} | {
    bank_account: null;
} {
    return value == AccountType.loan ? {
        loan: null
    } : value == AccountType.investment ? {
        investment: null
    } : value == AccountType.credit_card ? {
        credit_card: null
    } : value == AccountType.bank_account ? {
        bank_account: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
